'use client'
import { useState } from 'react'
import type { BrandColors, BrandGuardRules } from '@/types/schemas'
import { useBuilderStore } from '@/lib/builderStore'
import { AdvisoryPanel } from './AdvisoryPanel'

const norm = (s: string) => s.trim().toLowerCase()

export function ColorPicker({
  colorKey, guards, advisoryMode,
}: {
  colorKey: keyof BrandColors
  guards: BrandGuardRules | null
  advisoryMode: 'conversational' | 'structured'
}) {
  const value = useBuilderStore((s) => s.draftToken?.colors[colorKey] ?? '#000000')
  const updateColor = useBuilderStore((s) => s.updateColor)
  const [touched, setTouched] = useState(false)

  const allowed = (guards?.allowed_color_palette ?? []).map(norm)
  const outsidePalette = touched && allowed.length > 0 && !allowed.includes(norm(value))
  const rule = guards?.rules.find((r) => r.field === colorKey)
  const showAdvisory = outsidePalette && rule

  const apply = (v: string) => { setTouched(true); updateColor(colorKey, v) }

  return (
    <div className="flex flex-col gap-1">
      <label className="text-xs uppercase tracking-wide text-neutral-500 flex items-center gap-2">
        {colorKey}
        <span className="text-[9px] text-emerald-400">✦ Generated by Qwen</span>
      </label>
      <div className="flex items-center gap-2">
        <input type="color" aria-label={`${colorKey} swatch`} value={value}
               onChange={(e) => apply(e.target.value)} className="w-8 h-8 rounded cursor-pointer bg-transparent" />
        <input data-testid="hex-input" value={value} onChange={(e) => apply(e.target.value)}
               className="flex-1 text-sm font-mono bg-transparent border border-neutral-700 rounded px-2 py-1" />
      </div>
      {showAdvisory && <AdvisoryPanel rule={rule!} mode={advisoryMode} />}
    </div>
  )
}
